package pojos;
// Generated 13 feb. 2023 8:50:08 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Fabricantes generated by hbm2java
 */
public class Fabricantes implements java.io.Serializable {

    private String cif;
    private String nombre;
    private String descrip;
    private String domicilio;
    private Set productoses = new HashSet(0);

    public Fabricantes() {
    }

    public Fabricantes(String cif) {
        this.cif = cif;
    }

    public Fabricantes(String cif, String nombre, String descrip, String domicilio, Set productoses) {
        this.cif = cif;
        this.nombre = nombre;
        this.descrip = descrip;
        this.domicilio = domicilio;
        this.productoses = productoses;
    }

    public String getCif() {
        return this.cif;
    }

    public void setCif(String cif) {
        this.cif = cif;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescrip() {
        return this.descrip;
    }

    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    public String getDomicilio() {
        return this.domicilio;
    }

    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    public Set getProductoses() {
        return this.productoses;
    }

    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }

    @Override
    public String toString() {
        return "Fabricantes{" + "cif=" + cif + ", nombre=" + nombre + ", descrip=" + descrip + ", domicilio=" + domicilio + ", productoses=" + productoses + '}';
    }
}
